# version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    platform: linux/amd64  # Force use of AMD64 architecture
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    platform: linux/amd64  # Force use of AMD64 architecture
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example

volumes:
  db_data:
